apiVersion: batch/v1
kind: Job
metadata:
  name: get-info
spec:
  template:
    spec:
      containers:
      - name: get-info-job
        image: godlykser/kodem-entry-exercise:latest
      restartPolicy: Never
  ttlSecondsAfterFinished: 100