apiVersion: batch/v1
kind: Job
metadata:
  name: get-info-job
spec:
  template:
    metadata:
      name: get-info-job
    spec:
      volumes:
      - name: api-query-volume
        configMap:
          name: api-query-script
      containers:
      - name: get-info-job
        image: bitnami/kubectl
        volumeMounts:
        - mountPath: /api-query
          name: api-query-volume
        env:
        - name: HOME
          value: /tmp
        command: 
          - /bin/sh
          - -c
          - |
            ls -lh /api-query
            cp /api-query/api-query.sh /tmp
            chmod +x /tmp/api-query.sh
            /tmp/api-query.sh
            kubectl get all -o custom-columns=name:.metadata.name,type:.kind,namespace:.metadata.namespace,uid:.metadata.uid > ./data.json
      restartPolicy: Never
  backoffLimit: 3
  ttlSecondsAfterFinished: 30
  

---
apiVersion: v1
items:
- apiVersion: v1
  data:
    api-query.sh: |
      APISERVER=https://kubernetes.default.svc
      SERVICEACCOUNT=/var/run/secrets/kubernetes.io/serviceaccount
      NAMESPACE=$(cat ${SERVICEACCOUNT}/namespace)
      TOKEN=$(cat ${SERVICEACCOUNT}/token)
      CACERT=${SERVICEACCOUNT}/ca.crt
      curl --cacert ${CACERT} --header "Authorization: Bearer ${TOKEN}" -X GET ${APISERVER}/api
  kind: ConfigMap
  metadata:
    creationTimestamp: null
    name: api-query-script
kind: List
metadata: {}